#cloud-config

write_files:

  - content: |
      - hosts: localhost
        pre_tasks:
          - name: stop consul
            service: name=consul state=stopped
          - name: clean /opt/consul/data/serf/local.keyring
            file: path=/opt/consul/data/serf/local.keyring state=absent
          - name: Run database container
            docker_container:
              name: 'db'
              image: 'mariadb'
              state: 'started'
              network_mode: "host"
              restart_policy: "always"
              ports:
                - "3306:3306"
              env:
                MYSQL_ROOT_PASSWORD: '${db_password}'
          - name: Run Wordpress container
            docker_container:
              name: 'wp'
              image: 'wordpress'
              state: 'started'
              network_mode: "host"
              restart_policy: "always"
              ports:
                - "80:80"
              env:
                WORDPRESS_DB_HOST: '${db_host}'
                WORDPRESS_DB_USER: '${db_user}'
                WORDPRESS_DB_PASSWORD: '${db_password}'
        roles:
          - role: entercloudsuite.consul
            consul_config_validate: "{{ consul_user_home }}/bin/consul validate -config-format=json %s"
            consul_configs:
              main:
                bind_addr: "{{ ansible_default_ipv4.address }}"
                client_addr: "0.0.0.0"
                node_name: "{{ ansible_hostname }}"
                data_dir: "{{ consul_data_dir }}"
                encrypt: "${consul_encrypt}"
                datacenter: "${consul_datacenter}"
                enable_syslog: true
                server: false
                ui: true
                enable_script_checks: true
                services:
                  - name: "${name}"
                    checks:
                      - http: "http://127.0.0.1:80"
                        method: "GET"
                        interval: "2s"
                  - name: "exporter_node"
                    port: 9100
                rejoin_after_leave: true
                retry_join:
                  - "${consul}"
    path: /usr/src/cloud/playbook.yml
    permissions: '0400'

runcmd:
  - |
      bash <<'EOF'
      export COMPLETED=false
      while [ "$COMPLETED" == "false" ]; do
        (
          set -e errexit
          set -o pipefail
          # workaround https://github.com/ansible/ansible/issues/21562
          export HOME=/root
          cd /usr/src/cloud
          source venv/bin/activate
          ansible-playbook -e ansible_python_interpreter=/usr/bin/python --connection=local playbook.yml
        ) >> /var/log/cloud-scripts.log 2>&1
        if [ $? == 0 ]; then
          COMPLETED=true
        fi
        sleep 1
      done
      EOF
